@startuml
title           Работа с тестами

start

partition Преподаватель {
    :Создает тест;
    :Выбирает тип теста;
    :Сохраняет тест в систему;
}

partition Студент {
    :Открывает список доступных тестов;
    :Проходит тест;
    if (Тип теста = "Кодовый") then (да)
        :Отправляет код на проверку;
        -Преподаватель : Переход на ручную проверку
    else (нет)
        :Ответ сохраняется;
        :Система оценивает результат;
        :Баллы сохраняются;
        stop
    endif
}

partition Преподаватель {
    :Получает кодовый ответ;
    :Оценивает вручную;
    :Выставляет баллы;
    :Сохраняет результат;
}

stop
@enduml
